-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-05-24 00:40:23 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE country (
    country VARCHAR2(30) NOT NULL
);

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( country );

CREATE TABLE disease (
    disease VARCHAR2(40) NOT NULL
);

ALTER TABLE disease ADD CONSTRAINT disease_pk PRIMARY KEY ( disease );

CREATE TABLE diseasesymptom (
    disease          VARCHAR2(40) NOT NULL,
    symptom_symptom  VARCHAR2(40) NOT NULL
);

ALTER TABLE diseasesymptom ADD CONSTRAINT diseasesymptom_pk PRIMARY KEY ( disease,
                                                                          symptom_symptom );

CREATE TABLE person (
    id    INTEGER NOT NULL,
    name  VARCHAR2(30)
);

ALTER TABLE person ADD CONSTRAINT person_pk PRIMARY KEY ( id );

CREATE TABLE personcountry (
    person_id        INTEGER NOT NULL,
    country_country  VARCHAR2(30) NOT NULL,
    data             DATE NOT NULL
);

ALTER TABLE personcountry ADD CONSTRAINT personcountry_pk PRIMARY KEY ( data,
                                                                        person_id );

CREATE TABLE sick (
    person_id        INTEGER NOT NULL,
    data             DATE NOT NULL,
    symptom_symptom  VARCHAR2(40) NOT NULL
);

ALTER TABLE sick
    ADD CONSTRAINT sick_pk PRIMARY KEY ( data,
                                         person_id,
                                         symptom_symptom );

CREATE TABLE symptom (
    symptom VARCHAR2(40) NOT NULL
);

ALTER TABLE symptom ADD CONSTRAINT symptom_pk PRIMARY KEY ( symptom );

ALTER TABLE diseasesymptom
    ADD CONSTRAINT diseasesymptom_disease_fk FOREIGN KEY ( disease )
        REFERENCES disease ( disease );

ALTER TABLE diseasesymptom
    ADD CONSTRAINT diseasesymptom_symptom_fk FOREIGN KEY ( symptom_symptom )
        REFERENCES symptom ( symptom );

ALTER TABLE personcountry
    ADD CONSTRAINT personcountry_country_fk FOREIGN KEY ( country_country )
        REFERENCES country ( country );

ALTER TABLE personcountry
    ADD CONSTRAINT personcountry_person_fk FOREIGN KEY ( person_id )
        REFERENCES person ( id );

ALTER TABLE sick
    ADD CONSTRAINT sick_person_fk FOREIGN KEY ( person_id )
        REFERENCES person ( id );

ALTER TABLE sick
    ADD CONSTRAINT sick_symptom_fk FOREIGN KEY ( symptom_symptom )
        REFERENCES symptom ( symptom );




-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             13
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
