CREATE TYPE SICK_ROW_TYPE AS OBJECT (
    PERSON_ID NUMBER(38,0),
    PERSON_NAME VARCHAR2 (30 BYTE),
    SICK_DATE DATE,
    SYMPTOM VARCHAR2 (40 BYTE)
    );
/        
CREATE TYPE SICK_TABLE_TYPE is TABLE of SICK_ROW_TYPE;
/
CREATE OR REPLACE FUNCTION SICK_PIPE(SICK_DATE DATE DEFAULT '01012020', F_SYMPTOM VARCHAR2 DEFAULT 'Fever')
RETURN SICK_TABLE_TYPE
PIPELINED
AS
    CURSOR MY_CUR IS 
        SELECT PERSON.ID, PERSON.NAME, SICK.DATA, SICK.SYMPTOM_SYMPTOM
        FROM SICK JOIN PERSON ON SICK.PERSON_ID = PERSON.ID
        WHERE SICK.SYMPTOM_SYMPTOM = F_SYMPTOM AND SICK.DATA > SICK_DATE;
    PERSON_ID_F NUMBER(38,0);
    PERSON_NAME_F VARCHAR2 (30 BYTE);
    SICK_DATE_F DATE;
    SYMPTOM_F VARCHAR2 (40 BYTE);
BEGIN  
    OPEN MY_CUR;
    LOOP
        FETCH MY_CUR INTO PERSON_ID_F, PERSON_NAME_F, SICK_DATE_F, SYMPTOM_F;
        EXIT WHEN MY_CUR%NOTFOUND;
        PIPE ROW(SICK_ROW_TYPE(PERSON_ID_F, PERSON_NAME_F, SICK_DATE_F, SYMPTOM_F));
    END LOOP;
END;
