CREATE OR REPLACE PACKAGE SICK_PKG IS
    
    TYPE SICK_ROW_TYPE IS RECORD (
        PERSON_ID SICK.PERSON_ID%TYPE,
        PERSON_NAME PERSON.NAME%TYPE,
        SICK_DATE SICK.DATA%TYPE,
        SYMPTOM SICK.SYMPTOM_SYMPTOM%TYPE
        );
        
    TYPE SICK_TABLE_TYPE is TABLE of SICK_ROW_TYPE;
    
    FUNCTION SICK_PIPE(SICK_DATE DATE DEFAULT '01012020', F_SYMPTOM VARCHAR2 DEFAULT 'Fever')
    RETURN SICK_TABLE_TYPE
    PIPELINED;
    
    PROCEDURE ADD_SYMPTOM (SYMPTOM_IN IN SYMPTOM.SYMPTOM%TYPE, PERSON_IN IN PERSON.ID%TYPE);
    
END SICK_PKG;
/
CREATE OR REPLACE PACKAGE BODY SICK_PKG is

        FUNCTION SICK_PIPE(SICK_DATE DATE DEFAULT '01012020', F_SYMPTOM VARCHAR2 DEFAULT 'Fever')
        RETURN SICK_TABLE_TYPE
        PIPELINED
        IS
        BEGIN    
            FOR SICK_ITERATOR IN (
                    SELECT PERSON.ID, PERSON.NAME, SICK.DATA, SICK.SYMPTOM_SYMPTOM
                    FROM SICK JOIN PERSON ON SICK.PERSON_ID = PERSON.ID
                    WHERE SICK.SYMPTOM_SYMPTOM = F_SYMPTOM AND SICK.DATA > SICK_DATE
                    )
            LOOP
                PIPE ROW(SICK_ITERATOR);
            END LOOP;     
        END;

        PROCEDURE ADD_SYMPTOM (SYMPTOM_IN IN SYMPTOM.SYMPTOM%TYPE, PERSON_IN IN PERSON.ID%TYPE)
        IS
        SYMPTOM_NUM INT := 0;
        PERSON_NUM INT := 0;
        NUM_EXP EXCEPTION;
        BEGIN
            SELECT COUNT(*) INTO SYMPTOM_NUM FROM SYMPTOM
            WHERE SYMPTOM.SYMPTOM = SYMPTOM_IN;
            SELECT COUNT(*) INTO PERSON_NUM FROM PERSON
            WHERE PERSON.ID = PERSON_IN;
            IF (PERSON_NUM = 0 OR SYMPTOM_NUM = 0) THEN
                RAISE NUM_EXP;
            END IF;
            INSERT INTO SICK
            VALUES (PERSON_IN, SYSDATE , SYMPTOM_IN);
        EXCEPTION
            WHEN NUM_EXP
            THEN DBMS_OUTPUT.PUT_LINE('Wrong data');
            WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Something else went wrong - ' || SQLCODE ||' : ' || SQLERRM);
        END;

END SICK_PKG;
