CREATE OR REPLACE PROCEDURE ADD_SYMPTOM (SYMPTOM_IN IN SYMPTOM.SYMPTOM%TYPE, PERSON_IN IN PERSON.ID%TYPE)
IS
SYMPTOM_NUM INT := 0;
PERSON_NUM INT := 0;
NUM_EXP EXCEPTION;
BEGIN
    SELECT COUNT(*) INTO SYMPTOM_NUM FROM SYMPTOM
    WHERE SYMPTOM.SYMPTOM = SYMPTOM_IN;
    SELECT COUNT(*) INTO PERSON_NUM FROM PERSON
    WHERE PERSON.ID = PERSON_IN;
    IF (PERSON_NUM = 0 OR SYMPTOM_NUM = 0) THEN
        RAISE NUM_EXP;
    END IF;
    INSERT INTO SICK
    VALUES (PERSON_IN, SYSDATE , SYMPTOM_IN);
EXCEPTION
    WHEN NUM_EXP
    THEN DBMS_OUTPUT.PUT_LINE('Wrong data');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Something else went wrong - ' || SQLCODE ||' : ' || SQLERRM);
END;
