CREATE OR REPLACE TRIGGER SYMPTOM_TR
AFTER INSERT ON DISEASE
FOR EACH ROW
DECLARE 
    NEW_SYMPTOM SYMPTOM.SYMPTOM%TYPE := 'Fever';
BEGIN
    INSERT INTO DISEASESYMPTOM
    VALUES (:NEW.DISEASE, NEW_SYMPTOM);
END;
